apiVersion: v1
kind: Pod
metadata:
  name: pod-db-pos-tech
  labels:
        app: pod-db-pos-tech
spec:
  containers:
    - name: mongodb
      image: mongo
      ports:
        - containerPort: 27017