apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-api-pos-tech
  labels:
    app: pod-api-pos-tech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-api-pos-tech
  template:
    metadata:
      labels:
        app: pod-api-pos-tech
    spec:
      containers:
        - name: pod-api-pos-tech
          image: bviniciusilva/api-pos-tech-start:v23
          ports:
            - containerPort: 3000
          env: 
            -   name: MONGO_DATABASE
                valueFrom:
                  secretKeyRef:
                    name: pos-tech-opaque
                    key: MONGO_DATABASE
            -   name: MONGO_HOST
                valueFrom:
                  secretKeyRef:
                    name: pos-tech-opaque
                    key:  MONGO_HOST