apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-db-pos-tech
  name: svc-db-pos-tech
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32000
  selector:
    app: pod-db-pos-tech
  type: LoadBalancer